### ISSUE TITLE
点赞帖

### ISSUE THREAD

**Issue by bennyhuo** [douo/ActivityBuilder#1]
最近重构代码觉得启动 activity 的传参太随意，需要有这样一个框架来约束或者引导开发者去正确启动一个 Activity。

我开始搜了很久，阿里 Arouter 之类的也并不能满足需求，后来自己撸了一半apt，发现你这个，很赞~

**Comment by douo** [comment]
@enbandari 谢谢，不过这个库有个**致命**的缺点，回调代码不能跨进程，也不能在 App 被系统杀死后恢复。使用的时候要注意。

**Comment by bennyhuo** [comment]
@douo 了解~~

**Comment by bennyhuo** [comment]
@douo 回调代码不能跨进程，是说用 Fragment startActivityForResult 不支持跨进程？

**Comment by douo** [comment]
@enbandari 不是的，lambda 表达式实际上还是一个内部类的实例，持有外部类的 final 引用，很难被序列化，被杀死了就无法恢复（或者说很难）到原来的状态。`startActivityForResult` 只是方法区的一段代码而已，状态的保存和恢复，由 Activity 或 Fragment 来控制，比如序列化或者 `saveInstanceState` 方法。

**Comment by douo** [comment]
无状态的 lambda 就可以做恢复，不过这一块还没有做。我得重新考虑下这个库的应用场景。

**Comment by bennyhuo** [comment]
哎呀，我得去仔细看看你是怎么实现这块儿的了。。没有get到你的点。。。我其实没有想明白你说的场景，什么情况下杀掉了恢复还需要result，以及跨进程的问题，这块儿之前接触不多(⋟﹏⋞)

**Comment by bennyhuo** [comment]
我明白了，开发者选项不保留活动就可以复现你说的

**Comment by douo** [comment]
是的。实现是用 Headless Fragment 来实现的。

**Comment by bennyhuo** [comment]
我在我的框架用反射更新匿名内部类对 Activity 、Fragment、View 的引用，这种应该会有小概率的情况出现问题，但应该可以基本解决你说的Activity被销毁的这个问题。

**Comment by bennyhuo** [comment]
唯一不足的就是，用到了反射= =、其他地方都有不用反射的方案，唯独这个，没招了。

**Comment by douo** [comment]
@enbandari 666 我试了下这种方法应该是可行的，确实可以用反射修改 final 引用。

**Comment by douo** [comment]
对捕获的 View 之类的局部变量还是比较无力的。

**Comment by bennyhuo** [comment]
View和fragment我都是记录id然后重新用activity查，大多数情况下没什么问题应该

**Comment by douo** [comment]
哈哈，有意思。我看看剩下春节假期能不能撸出来。或有PR吗😆？

**Comment by bennyhuo** [comment]
木有。。我的实现在这个路径下面，比较直接。。https://github.com/enbandari/TieGuanYin/tree/master/runtime/src/main/java/com/bennyhuo/tieguanyin/runtime/result

**Comment by douo** [comment]
@enbandari 哦哦👌，我已经自己实现了: [AbstractActivityReferenceUpdater.java](https://github.com/douo/ActivityBuilder/blob/master/library/src/main/java/info/dourok/esactivity/reference/AbstractActivityReferenceUpdater.java)

**Comment by bennyhuo** [comment]
你的代码写的很漂亮，我要学习下，哈哈
